fix: update tuigreet package reference
The tuigreet package is now part of the greetd package set.
Updated from pkgs.tuigreet to pkgs.greetd.tuigreet.

This fixes the build error:
  error: attribute 'tuigreet' missing